blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: For general HA questions, please use the community forum
  - name: HACS support
    url: https://hacs.xyz/
    about: For HACS-related issues
